### ISSUE TITLE
React Login Page

### ISSUE THREAD

**Issue by takatanium** [mimlowe/pairat#1]

**Comment by mmenschig** [comment]
Currently getting a login page compile error
```

./src/App.js
Module not found: `/Users/mmenschig/Projects/ucb/pairat/app/client/src/components/Login/index.js` does not match the corresponding path on disk `LogIn`.
```

<img width="1027" alt="screen shot 2017-12-13 at 10 40 03 pm" src="https://user-images.githubusercontent.com/7193122/33978927-d695a2b2-e056-11e7-9096-2d76167e3b1f.png">
