### ISSUE TITLE
Mentions Table Schema

### ISSUE THREAD

**Issue by takatanium** [mimlowe/pairat#5]

**Comment by mmenschig** [comment]
@mattcarpowich1 @takatanium @mimlowe looking for input here from everyone.

What are we tracking exactly? Let's get a conversation going

**Comment by takatanium** [comment]
I'm thinking the minimum schema would be:
Sent From (User)
Sent To
Date
URL
Element

**Comment by takatanium** [comment]
we discussed this in depth
